### ISSUE TITLE
63C wording suggestions

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#573] opened 2017-02-28 18:27 UTC
### All Fields Are Required
**Organization Name (N/A, if individual):** State Department

**Organization Type (see below for codes)**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 63C

**Reference (Include section and paragraph number)**: Listed below with corresponding comments.
 
**Comment (Include rationale for comment)**:
Figure 4-2: Reference to CSPs should be to IdPs, to be consistent with use elsewhere and the text appearing immediately below.

Section 8.1, second occurrence of list item # 1: “…RP and the IdP need to be validated.”  Validated? Or Authenticated?  If former, elaborate a bit, or point to other clarifying text in the document.

**Suggested Change**: N/A
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment] 2017-03-01 20:55
First portion is a duplicate of #562

**Comment by paul-grassi** [comment] 2017-03-01 23:00
I'll close #562, mark as dupe, and we'll work of this agency feedback.  Thanks!

**Closed as completed** 2017-03-03 18:58 UTC
Labels: accepted, 63C, editorial
