### ISSUE TITLE
Use of 'digital service' seems to be vague and inconsistent 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1533] opened 2017-04-03 17:13 UTC
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 2, 1, first three sentences
 
**Comment (Include rationale for comment)**:  Use of 'digital service' seems to be vague and inconsistent
 
In the first instance 'digital service' could easily be (was understood to be) the identity provider.  The assertion is entirely consistent in that reading.  However, in the sense of "accessing a digital service" it seems that the digital service is something else, e.g. a service which may be an RP.  Clarity is required.

**Suggested Change**: Accept 'digital service' as being a generic term which needn't be quantified, but in the first instance (second sentence) be specific - refer to a Credential-issuing Service.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment] 2017-04-07 03:03
Duplicate of #1071.

**Closed as completed by jimfenton** 2017-04-07 03:03 UTC
Labels: duplicate, 63B
