### ISSUE TITLE
"SHOULD be performed locally on claimant’s device or MAY" … 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1581] opened 2017-04-03 17:14 UTC
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.2.3, 10
 
**Comment (Include rationale for comment)**:  "SHOULD be performed locally on claimant’s device or MAY" …
 
… adds a conflicting form of expression to the 'SHOULD' clause, making it uncertain whether biometric matching is required at all.  Moreover, since this section is about biometric matching there need be no 'SHOULD' about it.  

**Suggested Change**: Either remove the 'MAY' or replace the 'or' with 'but', though see the following comment which encompases this.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment] 2017-04-12 18:04
Duplicate of #682

**Closed as completed by jimfenton** 2017-04-12 18:04 UTC
Labels: duplicate, 63B, Biometrics
