### ISSUE TITLE
Authenticated protected channel communications

### ISSUE THREAD

**Issue by DoD-CIO-ID2** [usnistgov/800-63-3#1277] opened 2017-03-31 20:12 UTC
### All Fields Are Required

**Organization Name (N/A, if individual):**
DoD-CIO-ID2

**Organization Type (see below for codes)**:
1

**Document (63-3, 63A, 63B, or 63C)**:
63B

**Reference (Include section and paragraph number)**:
 4.3.2

**Comment (Include rationale for comment)**:
 In 4.3.2, communication via an authenticated protected channel should be done between a 'claimant and verifier,' not a 'claimant and channel.'

**Suggested Change**:
 Amend the first sentence of 4.3.2 to read: "Communication between the claimant and verifier SHALL be via an authenticated protected channel.

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment] 2017-04-25 15:51
Duplicate of #795.

**Closed as completed by jimfenton** 2017-04-25 15:51 UTC
Labels: duplicate, 63B
