### ISSUE TITLE
Tables carry many internal inconsistencies and the terms used are not sufficiently distinct to allow a real sense of separation between such labels 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1516] opened 2017-04-03 16:50 UTC
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Tables 5.1, 5.2, 5.3, 
 
**Comment (Include rationale for comment)**:  Tables carry many internal inconsistencies and the terms used are not sufficiently distinct to allow a real sense of separation between such labels
 
These tables carry many internal inconsistencies and the terms used are not sufficiently distinct to allow a real sense of separation between such labesl as Fair/Adequate | Strong | Superior

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment] 2017-04-03 18:24
Duplicate of #1523

**Closed as completed by paul-grassi** 2017-04-03 18:24 UTC
Labels: duplicate, 63A
