### ISSUE TITLE
"Of which exists ..." is grammatically flawed and seems to add noithing 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1535] opened 2017-04-03 17:13 UTC
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 2, 1
 
**Comment (Include rationale for comment)**:  "Of which exists ..." is grammatically flawed and seems to add noithing
 

**Suggested Change**: Remove whole sentence
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment] 2017-04-06 03:50
Duplicate of #572. Fixed by #579.

**Closed as completed by jimfenton** 2017-04-06 03:50 UTC
Labels: duplicate, 63B, editorial
