### ISSUE TITLE
It would be worth noting that these are just tests on possession of an authenticator of the factor ‘something you have’. This is also true 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1242] opened 2017-03-31 16:32 UTC
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.1.2 Look-up secrets, 
 
**Comment (Include rationale for comment)**:  It would be worth noting that these are just tests on possession of an authenticator of the factor ‘something you have’. This is also true of Out-of-band.
 

**Suggested Change**: It would be worth noting that these are just tests on possession of an authenticator of the factor ‘something you have’. This is also true of Out-of-band.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment] 2017-04-25 03:33
Duplicate of #850.

**Closed as completed by jimfenton** 2017-04-25 03:33 UTC
Labels: duplicate, 63B
