### ISSUE TITLE
Out-of-band is not an authentication factor. It is a test of possession of an authenticator – usually something you have. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1253] opened 2017-03-31 16:45 UTC
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 8.1 Authentic-ator Threats, 1
 
**Comment (Include rationale for comment)**:  Out-of-band is not an authentication factor. It is a test of possession of an authenticator – usually something you have.

 
The other thing to note it that for an eavesdropping threat it is stronger than a number of ‘something you know’ due to it not being a static value session to session.

**Suggested Change**: Rather than rule it out, put it in context.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment] 2017-04-25 03:52
Duplicate of #808.

**Closed as completed by jimfenton** 2017-04-25 03:52 UTC
Labels: duplicate, 63B
