### ISSUE TITLE
What presents multiple opportunities? Of which exists multiple opportunities for impersonation and other attacks to fraudulently claim another subject’s digital identity. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#844] opened 2017-03-30 22:18 UTC
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 2, 1
 
**Comment (Include rationale for comment)**:  What presents multiple opportunities? Of which exists multiple opportunities for impersonation and other attacks to fraudulently claim another subject’s digital identity.
 
"Digital identity presents a technical challenge because this process often involves the proofing of individuals over an open network, and always involves the authentication of individual subjects over an open network to access digital government services. Of which exists multiple opportunities for impersonation and other attacks to fraudulently claim another subject’s digital identity."

**Suggested Change**: Of which what? The process of authenticating, of Identity proofing or… Cannot suggest a rewrite at this time. It just seems very awkward the way it is written.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment] 2017-04-06 03:49
Duplicate of #572. Fixed by #579.

**Closed as completed by jimfenton** 2017-04-06 03:49 UTC
Labels: duplicate, 63B, editorial
