### ISSUE TITLE
This section is on single-factor OTP devices but refers to a 'multi-factor OTP authenticator'. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1643] opened 2017-04-10 17:11 UTC
**Organization Name (N/A, if individual)**: DHS S&T FRG

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.1.4.2, 2nd para, 1st line
 
**Comment (Include rationale for comment)**:  This section is on single-factor OTP devices but refers to a 'multi-factor OTP authenticator'.
 
Cut and paste error.

**Suggested Change**: Change to read “When a single-factor OTP authenticator …”
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment] 2017-04-10 20:44
Duplicate of #510.

**Closed as completed by jimfenton** 2017-04-10 20:44 UTC
Labels: duplicate, 63B
