### ISSUE TITLE
Confusing wording and use of "authenticator" in 63-3

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#568] opened 2017-02-28 18:03 UTC
### All Fields Are Required
**Organization Name (N/A, if individual):** State Department

**Organization Type (see below for codes)**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 63-3

**Reference (Include section and paragraph number)**: Section 4.3.1, Paragraph 5, 1st Sentence
 
**Comment (Include rationale for comment)**: Second use of authenticator here is unclear, and the antecedent of the final clause is also unclear.  Subscribers need not share which, “symmetric keys and memorized secrets, or asymmetric keys?”  Further second use of authenticator is vague – do you mean the authenticator token, the individual authenticating, or the service providing the authentication?  Maybe you mean verifier here?
 
**Suggested Change**: N/A
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment] 2017-02-28 21:50
Duplicate of #550

**Closed as completed by paul-grassi** 2017-02-28 21:50 UTC
Labels: duplicate, 63-3, editorial
