### ISSUE TITLE
63A wording suggestions/corrections + vagueness in Section 6, list item #2

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#571] opened 2017-02-28 18:15 UTC
### All Fields Are Required
**Organization Name (N/A, if individual):** State Department

**Organization Type (see below for codes)**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 63A

**Reference (Include section and paragraph number)**: Listed below with corresponding comments.
 
**Comment (Include rationale for comment)**:
Section 2.2, Paragraph 4 (?): “At IAL2 and IAL3, pseudonymity in federated environment is enabled by limiting the number of attributes sent from the CSP…”  Notwithstanding that the IdP and CSP may be one and the same in many instances, for consistency’s sake, you should say “from the IdP” as you have previously as attributes originate within the IdP process/provider.

Section 4.2, List item # 4: “… including whether the such attributes…”  Delete the word “the” 

Table 4-3  Cell for intersection of row “Resolution” and Column “IAL3” is null.  Second half of entry for cell at intersection of row “evidence” and column “IAL3” references “ADEQUATE” evidence, which is not a defined class of evidence.  Perhaps you mean “FAIR?”

Section 6, Paragraph 2: “The definition of derived in this section does not infer…”  This comment may (perhaps should not) be passed, but “infer?”  Notwithstanding that due to regular abuse, imply and infer are now considered synonyms by the lexicographers, you are authoring the document and are speaking in the active voice, “imply” is conventionally the better word to use here.

Section 6, List item # 2: Get it generally, but this is vague, could use more specifics.

Section 6, Box text, last sentence: “… the authenticator will can be used…”  Pick one, “will” or “can”.

**Suggested Change**: N/A
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment] 2017-03-02 00:13
3rd comment is a duplicate of #518  and fixed with PR #520.

**Comment by paul-grassi** [comment] 2017-03-02 00:16
Comment 1 - No change needed.  We already acknowledge that an IDP and CSP are the same.  We are specific that pseudonymity is only possible in federated environments when the CSP and RP are **not** the same.

**Closed as completed** 2017-03-04 05:07 UTC
Labels: 63A, editorial, partially-accepted
