### ISSUE TITLE
Language around "something you are" being able to be replicated does not take into account behavioral biometrics. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#652] opened 2017-03-22 18:01 UTC
**Organization Name (N/A, if individual)**: BioCatch

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 8.1, 
 
**Comment (Include rationale for comment)**:  Language around "something you are" being able to be replicated does not take into account behavioral biometrics.
 
Behavioral biometrics differ from physical biometrics as there is nothing to "steal" so they cannot be replicated.

**Suggested Change**: Provide clarification around behavioral biometrics as a modailty.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by enewt** [comment] 2017-04-11 17:09
Duplicate of #649

**Closed as completed by enewt** 2017-04-11 17:09 UTC
Labels: duplicate, 63B, Biometrics
