### ISSUE TITLE
"the digital service" is again used in an uncertain context 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1544] opened 2017-04-03 17:13 UTC
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 4, 5
 
**Comment (Include rationale for comment)**:  "the digital service" is again used in an uncertain context
 
Is this a service which is an RP seeking an authentication or or is it the authenticating service?

**Suggested Change**: Use a term which removes this doubt
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment] 2017-04-08 00:24
Duplicate of #1071.

**Closed as completed by jimfenton** 2017-04-08 00:24 UTC
Labels: duplicate, 63B
