### ISSUE TITLE
In subsequent authenticator sections (i.e., 5.1.4 onward), the introductory description in the box ends with what factor the authenticator represents in italics 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1642] opened 2017-04-10 17:11 UTC
**Organization Name (N/A, if individual)**: DHS S&T FRG

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.1.1, 5.1.2, 5.1.3, 
 
**Comment (Include rationale for comment)**:  In subsequent authenticator sections (i.e., 5.1.4 onward), the introductory description in the box ends with what factor the authenticator represents in italics 
 
(for example, “A single factor OTP device is something you have.”); however the first 3 sections omit this.  It may seem obvious, but including such a statement for all authenticators would be both more clear and consistent. Consistency & clarity.

**Suggested Change**: Recommend adding at the end of 5.1.1, “Memorized Secrets are something you know.”  Similarly, to 5.1.2 “Look-up Secrets are something you have.” and to 5.1.3 “Out-of-Band Authenticators are something you have.”
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment] 2017-04-10 20:33
Duplicate of #850.

**Closed as completed by jimfenton** 2017-04-10 20:33 UTC
Labels: duplicate, 63B
