### ISSUE TITLE
Clarify acceptance of user typing behavior biometrics authentication to meet AAL2

### ISSUE THREAD

**Issue by mingpeiwk** [usnistgov/800-63-3#1301] opened 2017-03-31 23:31 UTC
### All Fields Are Required
**Organization Name (N/A, if individual): Symantec

**Organization Type (see below for codes)**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 63-3, 63B

**Reference (Include section and paragraph number)**: 63B 5.2.3
 
**Comment (Include rationale for comment)**:
 
The authentication document specifies "Use of Biometrics", meaning largely the physical biometrics with reference example Facial etc. as an authenticator or unlocking an authenticator. The use of user behavior such as gaiting pattern or keyboard typing, or mobile typing isn't cited.

For the similar pattern matching, user identification with use of user behavior patterns should be accepted as authentication methods.

**Suggested Change**:

Clarify on use of user behavior biometrics in authentication, and acceptance to reach respective AAL, in particularly AAL2.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment] 2017-05-13 15:23
Duplicate of #649

**Closed as completed by jimfenton** 2017-05-13 15:23 UTC
Labels: duplicate, 63B, Biometrics
