### ISSUE TITLE
Is “authentication error” a false positive authentication, or something else? 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1219] opened 2017-03-31 16:31 UTC
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 2. Introduction, 5
 
**Comment (Include rationale for comment)**:  Is “authentication error” a false positive authentication, or something else?
 
The term “authentication error” may not be appropriate. Authentication is more or less binary depending on the successful use of the authenticator at the CSP. From the RP's perspective, there is a service authorisation risk that the user with possession of the authenticator is not the subscriber, but this is not an authentication error.  

**Suggested Change**: Use a term other than authentication error - or define what this means.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment] 2017-04-20 18:45
The interpretation that it is a false positive authentication is correct. Will clarify.

**Comment by jimfenton** [comment] 2017-05-08 20:25
Duplicate of #846

**Closed as completed by jimfenton** 2017-05-08 20:25 UTC
Labels: duplicate, 63B
