### ISSUE TITLE
Is authenticator correct?

### ISSUE THREAD

**Issue by AKD9** [usnistgov/800-63-3#631] opened 2017-03-16 20:27 UTC
### All Fields Are Required
**Organization Name (N/A, if individual):**  Fischer International Identity

**Organization Type (see below for codes)**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 63-3

**Reference (Include section and paragraph number)**: 4.3.1 paragraph 4 & 5
 
**Comment (Include rationale for comment)**: existing text shown below is confusing & contradicting.

**The private key is stored on the authenticator** and is used by the claimant to prove possession and control of the authenticator. A verifier, knowing the claimant’s public key through some credential (typically a public key certificate), can use an authentication protocol to verify the claimant’s identity, by proving that the claimant has possession and control of the associated private key authenticator.

Shared secrets stored on authenticators may be either symmetric keys or memorized secrets (e.g., passwords and PINs), as opposed to the **asymmetric keys described above, which subscribers need not share with the authenticator.** 
 
**Suggested Change**: The ending word **authenticator** should be changed to **verifier**.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment] 2017-03-16 21:18
Duplicate of #550

**Closed as completed by paul-grassi** 2017-03-16 21:18 UTC
Labels: duplicate, 63-3
